# {% set name = "lrose-core" %}
# {% set version = "3.8.2" %}

package:
  # name: {{ name|lower }}
  # version: {{ version }}
  name: "lrose-core"
  version: "3.0.0"

source:
  path: ../../../lrose-core/
  folder: out/

build:
  run_exports:
    - libnetcdf
    - l
  script_env:
    - INSTALL_PREFIX=../out
    - DESTDIR=../out
#   number: 0
#   script: |   #\u0022
#     FILE=./build
#     [ -d "$FILE" ] &&  rm -rf ./build/* || mkdir build;
#     cd build
#     cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX
#     cmake --build . --config Release
#     cmake --install .

requirements:
  build:
    - git
    - cmake
    - make
    - {{ compiler('cxx') }}
test:
  # imports:
  #   - ctest
  # requires:
  #   - gtest
  script_env:
    - INSTALL_PREFIX=./out
  commands:
    - $INSTALL_PREFIX/bin/RadMon -h
    - $INSTALL_PREFIX/bin/HawkEye -h

about:
  home: https://github.com/NCAR/lrose-core
  summary: "LROSE Lidar Radar Open Source E"
  description: |
    LROSE - The Lidar Radar Open Software Environment
    LROSE is a co-operative project between:
      Dept. of Atmospheric Science at Colorado State University (CSU) and the
      The Earth Observing Lab at the National Center for Atmospheric Research (NCAR).
    LROSE is funded by the National Science Foundation.

    LROSE CORE REPOSITORY
      This GitHub distribution contains the core software for LROSE.

    To download this repository from GitHub, run:
      git clone https://github.com/NCAR/lrose-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SKF
